<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:p1="urn:KFC_I_SYSTEMA:entrada:confirmacion" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" name="ConfirmacionEntrada_In" targetNamespace="urn:KFC_I_SYSTEMA:entrada:confirmacion">
  <wsdl:documentation/>
  <wsp:UsingPolicy wsdl:required="true"/>
  <ifw:properties xmlns:ifw="urn:com-sap:ifr:v2:wsdl">
    <ifw:category>ifmmessif</ifw:category>
    <ifw:VersionID>baf86f06d09711ebc9e500000046f7c6</ifw:VersionID>
    <ifw:lifeCycleInfo>
      <objectState/>
      <objectstatus value="A"/>
      <personresponsible value="administrator"/>
      <changed by="administrator" on="1624063699633"/>
    </ifw:lifeCycleInfo>
    <ifw:runtimeVersion uri="urn:sap-com:soap:xms:application:xip"/>
    <ifw:communicationProfile uri="prf_dt_if_com_stateless"/>
    <ifw:securityProfile uri="prf_dt_if_sec_basic"/>
    <ifw:interfacePattern p2p="true"/>
    <ifw:isSensitiveData>false</ifw:isSensitiveData>
    <ifw:classifications>
      <ifw:classification name="ObjectType" namespace="http://uddi.sap.com/classification" uddikey="uddi:uddi.sap.com:categorization:object-type" valueCode="ifmmessif"/>
      <ifw:classification name="ObjectID" namespace="http://uddi.sap.com/classification" uddikey="uddi:uddi.sap.com:categorization:object-id" valueCode="45e60c5d6f2638a6902178b197607186"/>
    </ifw:classifications>
    <ifw:additionalAttributes/>
    <ifw:methods>
      <ifw:method name="ConfirmacionEntrada_In">
        <ifw:isSynchron>false</ifw:isSynchron>
        <ifw:isIdempotent>false</ifw:isIdempotent>
        <ifw:isInbound>true</ifw:isInbound>
        <ifw:interfaceCategory>inbound</ifw:interfaceCategory>
        <ifw:communicationProfile uri="prf_dt_op_com_async"/>
        <ifw:contextobjects/>
      </ifw:method>
    </ifw:methods>
    <ifw:messages>
      <ifw:message name="ConfirmacionEntradaRequest">
        <ifw:messType>ifmmessage</ifw:messType>
        <ifw:keyElements>
          <ifw:elem id="NAME">ConfirmacionEntradaRequest</ifw:elem>
          <ifw:elem id="NAMESPACE">urn:KFC_I_SYSTEMA:entrada:confirmacion</ifw:elem>
        </ifw:keyElements>
        <ifw:technicalNamespace>urn:KFC_I_SYSTEMA:entrada:confirmacion</ifw:technicalNamespace>
        <ifw:VersionID>7ea5cdfcd09711ebb2dd00000046f7c6</ifw:VersionID>
        <ifw:xmlNamespace>urn:KFC_I_SYSTEMA:entrada:confirmacion</ifw:xmlNamespace>
        <ifw:dataType name="ConfirmacionEntrada" namespace="urn:KFC_I_SYSTEMA:entrada:confirmacion" swcvId="bf1e0b10d08f11ebb1cdf19cc0a88d08" uri="name=ConfirmacionEntrada~namespace=urn:KFC_I_SYSTEMA:entrada:confirmacion~swcvId=bf1e0b10d08f11ebb1cdf19cc0a88d08"/>
      </ifw:message>
    </ifw:messages>
    <ifw:matchingInterfaces/>
    <ifw:genericProperties>
      <ifw:swcvinfo>
        <ifw:guid>bf1e0b10d08f11ebb1cdf19cc0a88d08</ifw:guid>
        <ifw:name>KFC_I_SYSTEMA, 1 of kfc.com.ec</ifw:name>
      </ifw:swcvinfo>
      <ifw:languages>
        <ifw:language internalCode="EN" original="true"/>
      </ifw:languages>
      <ifw:documentation type="I">
        <name>_ID_45e60c5d6f2638a6902178b197607186_ifmmessif</name>
        <namespace>urn:KFC_I_SYSTEMA:entrada:confirmacion</namespace>
      </ifw:documentation>
    </ifw:genericProperties>
  </ifw:properties>
  <wsp:Policy wsu:Id="OP_ConfirmacionEntrada_In"/>
  <wsdl:types>
    <xsd:schema xmlns="urn:KFC_I_SYSTEMA:entrada:confirmacion" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:KFC_I_SYSTEMA:entrada:confirmacion">
      <xsd:element name="ConfirmacionEntradaRequest" type="ConfirmacionEntrada"/>
      <xsd:complexType name="ConfirmacionEntrada">
        <xsd:sequence>
          <xsd:element name="File" type="xsd:string"/>
          <xsd:element name="Confirmar" type="xsd:boolean"/>
        </xsd:sequence>
      </xsd:complexType>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="ConfirmacionEntradaRequest">
    <wsdl:documentation/>
    <wsdl:part element="p1:ConfirmacionEntradaRequest" name="ConfirmacionEntradaRequest"/>
  </wsdl:message>
  <wsdl:portType name="ConfirmacionEntrada_In">
    <wsdl:documentation/>
    <wsdl:operation name="ConfirmacionEntrada_In">
      <wsdl:documentation/>
      <wsp:Policy>
        <wsp:PolicyReference URI="#OP_ConfirmacionEntrada_In"/>
      </wsp:Policy>
      <wsdl:input message="p1:ConfirmacionEntradaRequest"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="ConfirmacionEntrada_InBinding" type="p1:ConfirmacionEntrada_In">
    <soap:binding xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="ConfirmacionEntrada_In">
      <soap:operation xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" soapAction="http://sap.com/xi/WebService/soap1.1"/>
      <wsdl:input>
        <soap:body xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" use="literal"/>
      </wsdl:input>
    </wsdl:operation>
  </wsdl:binding>
</wsdl:definitions>
